apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-varselbestiller
  namespace: personbruker
  labels:
    team: personbruker
spec:
  encFrom:
    - secret: dittnav-varselbestiller-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  prometheus:
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
    - "https://dittnav-varselbestiller-gcp.nais.oera.no"
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - name: varselbestiller
        type: POSTGRES_11
        tier: db-f1-micro
        diskType: SSD
        diskSize: 10
        diskAutoresize: false
        autoBackupTime: "03:00"
        databases:
          - name: varselbestiller
            envVarPrefix: DB
        maintenanceWindow:
          day: 1
          hour: 4
        cascadingDelete: false
  resources:
    limits:
      cpu: "3"
      memory: 1200Mi
    requests:
      cpu: "1"
      memory: 1024Mi
