apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-varselbestiller
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  prometheus:
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
    - "https://dittnav-varselbestiller.nais.oera.no"
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/sbs/dittnav-varselbestiller/personbruker
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /serviceuser/data/prod/srvdittnav-varsel-b
        mountPath: /secret/serviceuser
  resources:
    limits:
      cpu: "3"
      memory: 1200Mi
    requests:
      cpu: "1"
      memory: 1024Mi
